plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    id "maven-publish"
}

apply from: "../common_lib.gradle"

android {
    namespace 'com.xiaojinzi.support.init'
}

/*group = 'com.xiaojinzi.support'
archivesBaseName = "init"*/

apply from: "../common_publish.gradle"