plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    id "maven-publish"
}

apply from: "../common_lib.gradle"

/*group = 'com.xiaojinzi.support'
archivesBaseName = "ktx"*/

android {
    viewBinding {
        enabled = true
    }
    namespace 'com.xiaojinzi.support.ktx'
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    api project(':lib-bean')
    api project(':lib-init')
    api project(':lib-annotation')

    api libs.androidx.appcompat
    api libs.kotlin.stdlib
    api libs.kotlinx.coroutines
    api libs.rxjava
    api libs.rxandroid
    api libs.androidx.recyclerview
    api libs.androidx.acrivity.ktx
    api libs.androidx.lifecycle.viewmodel.ktx
    api libs.androidx.lifecycle.runtime.ktx
    api libs.androidx.lifecycle.runtime.ktx
    api libs.gson

}

apply from: "../common_publish.gradle"
