apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

apply from: "../common_lib.gradle"

/*group = 'com.xiaojinzi.support'
archivesBaseName = "ktx"*/

android {
    viewBinding {
        enabled = true
    }
    namespace 'com.xiaojinzi.support.ktx'
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    api project(':lib-bean')
    api project(':lib-init')
    api project(':lib-annotation')

    api libs.appcompat
    api libs.kotlin.stdlib
    api libs.kotlinx.coroutines
    api libs.rxjava
    api libs.rxandroid
    api libs.recyclerview
    api libs.acrivity.ktx
    api libs.lifecycle.viewmodel.ktx
    api libs.lifecycle.runtime.ktx
    api libs.lifecycle.runtime.ktx
    api libs.gson

}

apply from: "../common_publish.gradle"
