plugins {
    id "com.android.library"
    alias(libs.plugins.compose.compiler)
    id "kotlin-android"
    id "maven-publish"
}

apply from: "../common_lib.gradle"

/*group = 'com.xiaojinzi.support'
archivesBaseName = "compose"*/

android {
    buildFeatures {
        // Enables Jetpack Compose for this module
        compose true
    }
    namespace 'com.xiaojinzi.support.compose'
}

dependencies {

    api project(':lib-ktx')

    api platform(libs.compose.bom)

    api libs.compose.ui.tooling
    api libs.compose.ui.tooling.preview
    api libs.compose.viewmodel
    api libs.activity.compose
    api libs.compose.ui
    api libs.compose.material
    api libs.compose.material3
    // api libs.compose_ui_foundation
    api libs.compose.constraintlayout
    api libs.accompanist.sysuicontrol

}

apply from: "../common_publish.gradle"