plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    id "maven-publish"
}

apply from: "../common_lib.gradle"

android {
    namespace 'com.xiaojinzi.support.architecture'
}

/*group = 'com.xiaojinzi.support'
archivesBaseName = "architecture"*/

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    api project(':lib-annotation')
    api project(':lib-ktx')
    api libs.androidx.activity
    api libs.rxjava
    api libs.rxkotlin
}

apply from: "../common_publish.gradle"