[versions]
gradle = "8.7.2"
compileSdk = "35"
minSdk = "21"
targetSdk = "35"
component = "8c968cf766"
compose = "1.7.5"
compose-kotlin-compiler-extension = "1.5.15"
compose-material-version = "1.7.5"
compose-material3-version = "1.3.1"
accompanist-version = "0.36.0"
# kotlin = "1.9.25"
kotlin = "2.0.21"
# kotlin-ksp = "1.9.25-1.0.20"
kotlin-ksp = "2.0.21-1.0.26"
kotlin-coroutines = "1.9.0"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-android = { group = "org.jetbrains.kotlin", name = "kotlin-android-extensions-runtime", version.ref = "kotlin" }

androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.15.0" }
androidx-activity = { group = "androidx.activity", name = "activity", version = "1.9.3" }
androidx-acrivity-ktx = { group = "androidx.activity", name = "activity-ktx", version = "1.9.3" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version = "1.8.5" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.3.2" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.8.7" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.8.7" }

rxandroid = { group = "io.reactivex.rxjava2", name = "rxandroid", version = "2.1.1" }
rxjava = { group = "io.reactivex.rxjava2", name = "rxjava", version = "2.2.21" }
rxkotlin = { group = "io.reactivex.rxjava2", name = "rxkotlin", version = "2.4.0" }

android-networking = { group = "com.amitshekhar.android", name = "android-networking", version = "1.0.2" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.11.0" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.11.0" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-rx = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-rx2", version.ref = "kotlin-coroutines" }

# Compose dependencies
compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2024.10.01" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.8.7" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.9.3" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose-material-version" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3-version" }
compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version = "1.1.0" }
compose-ui-foundation = { group = "androidx.ui", name = "ui-foundation", version = "0.1.0-dev14" }

# Compose support libraries
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist-version" }
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanist-version" }
accompanist-insets = { group = "com.google.accompanist", name = "accompanist-insets", version.ref = "accompanist-version" }
accompanist-sysuicontrol = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist-version" }
accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "accompanist-version" }
accompanist-placeholder = { group = "com.google.accompanist", name = "accompanist-placeholder", version.ref = "accompanist-version" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist-version" }
accompanist-webview = { group = "com.google.accompanist", name = "accompanist-webview", version.ref = "accompanist-version" }

# Component dependencies
component-annotation = { group = "com.github.xiaojinzi123.KComponent", name = "kcomponent-annotation", version.ref = "component" }
component-compiler = { group = "com.github.xiaojinzi123.KComponent", name = "kcomponent-compiler", version.ref = "component" }
component-impl = { group = "com.github.xiaojinzi123.KComponent", name = "kcomponent", version.ref = "component" }
component-impl-rx = { group = "com.github.xiaojinzi123.KComponent", name = "kcomponent-rx", version.ref = "component" }
component-plugin = { group = "com.github.xiaojinzi123.KComponent", name = "kcomponent-plugin", version.ref = "component" }

[plugins]
# com.android.library
android-application = {id = "com.android.application", version.ref = "gradle" }
android-library = {id = "com.android.library", version.ref = "gradle" }
kotlin-android = {id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-kapt = {id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin"}
kotlin-ksp = {id = "com.google.devtools.ksp", version.ref = "kotlin-ksp"}
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
